version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Openhearts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7281
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DB_HOST: db  # Используем имя сервиса вместо localhost
      DB_PORT: 5432
      DB_NAME: Openhearts
      DB_USER: postgres
      DB_PASSWORD: 7281
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  adminside:
    build: ./adminside
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./adminside:/usr/src/app
      - /usr/src/app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  db-data: